CREATE ROLE app LOGIN PASSWORD '${APP_PASS}';
GRANT CONNECT ON DATABASE db_store TO app;
GRANT USAGE ON SCHEMA warehouse TO app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA warehouse TO app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA warehouse TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA warehouse GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA warehouse GRANT USAGE, SELECT ON SEQUENCES TO app;

CREATE ROLE readonly LOGIN PASSWORD '${READONLY_PASS}';
GRANT CONNECT ON DATABASE db_store TO readonly;
GRANT USAGE ON SCHEMA warehouse TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA warehouse TO readonly;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA warehouse TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA warehouse GRANT SELECT ON TABLES TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA warehouse GRANT SELECT ON SEQUENCES TO readonly;

CREATE ROLE administrator LOGIN PASSWORD '${ADMINISTRATOR_PASS}';
GRANT CONNECT ON DATABASE db_store TO administrator;
GRANT USAGE ON SCHEMA warehouse TO administrator;
GRANT ALL PRIVILEGES ON DATABASE db_store to administrator;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA warehouse TO administrator;
ALTER DEFAULT PRIVILEGES IN SCHEMA warehouse GRANT ALL PRIVILEGES ON TABLES TO administrator;
ALTER DEFAULT PRIVILEGES IN SCHEMA warehouse GRANT ALL PRIVILEGES ON SEQUENCES TO administrator;